version: '3'

services:
  api:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - postgres_db
    networks: 
      - bth-network
    command: /bin/sh -c "yarn sequelize db:migrate && yarn start"
  web:
    build: ../frontend/.
    ports:
      - '3000:6000'
    networks: 
      - bth-network
    command: yarn serve
  postgres_db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bethehero
    ports:
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bth-network
volumes: 
  postgres-data:

networks: 
  bth-network: